before_install:
  - npm install -g grunt-cli
script:
  - echo "Don't mind me. I'm here for deployments only..."
after_success:
  - grunt ghrelease
language: node_js
node_js:
  - '0.10'
notifications:
  email: false
deploy:
  provider: npm
  email: stephan@boennemann.me
  api_key:
    secure: j/3R3qwblFEKbF4u9oa72bRy9G+/cAjnbIygN2KrOe4PbHBjj0i07Wm653ZESuesUUanf8n/Vv0gVn7XaLACWmZ+J1v8F9tkzt5/1k/cQwEQrlDQv7nsSCG+LkojM9WjYq22xMf7Vt1v7Nmy1tk6S2CQFTBZfJccPUePpa8MAxY=
  on:
    all_branches: true
    tags: true
    repo: hoodiehq/grunt-release-hoodie
env:
  global:
    - secure: "ur4jL3n00s61qoAUWreTS1dcV9Ni2w4o/cvLx5MsBcGKT+A556++OTqEoj8M/+dEEPpCAQpof9Iv+jgodG/jjT1cN6OBx0RtPOufXZi8eplfXhei+6dDOycYNnHO/r8dZIhki15lGmFV0/Vqor038RmVbkoaecOzynx6igf/jRw="
