before_install:
- npm install -g grunt-cli
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
language: node_js
node_js:
- '0.10'
notifications:
  email: false
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  api_key:
    secure: coLvcccwvm2yUeR49e2KHFhuYb3qAYdjwUJAaZ2hoMAVlAFiOJQH9vmNuvfCGg6xI8IL0nvMi3hr6e9rnU6okMTRISGu68+yV1Kxc0rm9LsM5qIzVUmX1CsNniv2oYqzb08sQqazcgBVRskLZjOARHormv7VyuErW5nkIwnf6tA=
  on:
    all_branches: true
    tags: true
env:
  global:
  - secure: "CS1RGaKIlIEDHtEe4AsBgNTcyGjxwroIvXJCV5xK6P3hPVL3TVXQfXgDql7VUeGl/Ce7HtAXpJvoUBmyETXZEGg0+i0BLDW3BhT7brigm44I6mVExGMo7VUwJ+UzcchTXb3NphRm9pEKy1DzDqdu5zPG+qNclY1TKFWu7GRVz2E="
